// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBkWu4rqhUWNzF6M5Zz42-HRX_FzSyEH4',
    appId: '1:605410024465:web:f15fc57bf87341b20aa5b0',
    messagingSenderId: '605410024465',
    projectId: 'chatapp1-cc462',
    authDomain: 'chatapp1-cc462.firebaseapp.com',
    storageBucket: 'chatapp1-cc462.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Aitnj9MTZtAs9jhC08e3BMBZHWWLyA4',
    appId: '1:605410024465:android:9a7609da8707355d0aa5b0',
    messagingSenderId: '605410024465',
    projectId: 'chatapp1-cc462',
    storageBucket: 'chatapp1-cc462.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXOsaWwFX6RL7Zg_QTlZscrcp3GauU7gk',
    appId: '1:605410024465:ios:3104c587b664d25c0aa5b0',
    messagingSenderId: '605410024465',
    projectId: 'chatapp1-cc462',
    storageBucket: 'chatapp1-cc462.appspot.com',
    iosBundleId: 'com.example.chatapp1',
  );
}
